# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/Mallory.ui'
#
# Created: Wed Jul 27 06:52:30 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(910, 828)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.tabWidget_2 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_interfaces = QtGui.QWidget()
        self.tab_interfaces.setObjectName(_fromUtf8("tab_interfaces"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.tab_interfaces)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.splitter_5 = QtGui.QSplitter(self.tab_interfaces)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_5.sizePolicy().hasHeightForWidth())
        self.splitter_5.setSizePolicy(sizePolicy)
        self.splitter_5.setMinimumSize(QtCore.QSize(0, 0))
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setHandleWidth(6)
        self.splitter_5.setChildrenCollapsible(True)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter_5)
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_5.addWidget(self.label_11)
        self.tableinterfaces = QtGui.QTableView(self.verticalLayoutWidget)
        self.tableinterfaces.setObjectName(_fromUtf8("tableinterfaces"))
        self.tableinterfaces.verticalHeader().setVisible(False)
        self.verticalLayout_5.addWidget(self.tableinterfaces)
        spacerItem = QtGui.QSpacerItem(16, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.btnsaveifcfg = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnsaveifcfg.sizePolicy().hasHeightForWidth())
        self.btnsaveifcfg.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/accept.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnsaveifcfg.setIcon(icon1)
        self.btnsaveifcfg.setObjectName(_fromUtf8("btnsaveifcfg"))
        self.horizontalLayout_17.addWidget(self.btnsaveifcfg)
        self.btnrefreshifaces = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnrefreshifaces.sizePolicy().hasHeightForWidth())
        self.btnrefreshifaces.setSizePolicy(sizePolicy)
        self.btnrefreshifaces.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/arrow_rotate_clockwise.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnrefreshifaces.setIcon(icon2)
        self.btnrefreshifaces.setObjectName(_fromUtf8("btnrefreshifaces"))
        self.horizontalLayout_17.addWidget(self.btnrefreshifaces)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.splitter_5)
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_8.addWidget(self.label_12)
        self.texteditdesc = QtGui.QPlainTextEdit(self.verticalLayoutWidget_2)
        self.texteditdesc.setReadOnly(True)
        self.texteditdesc.setObjectName(_fromUtf8("texteditdesc"))
        self.verticalLayout_8.addWidget(self.texteditdesc)
        self.horizontalLayout_12.addWidget(self.splitter_5)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/server_connect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_interfaces, icon3, _fromUtf8(""))
        self.tab_protocols = QtGui.QWidget()
        self.tab_protocols.setObjectName(_fromUtf8("tab_protocols"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.tab_protocols)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.splitterproto = QtGui.QSplitter(self.tab_protocols)
        self.splitterproto.setOrientation(QtCore.Qt.Horizontal)
        self.splitterproto.setObjectName(_fromUtf8("splitterproto"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.splitterproto)
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_9.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_9.addWidget(self.label_13)
        self.tableprotocols = QtGui.QTableView(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableprotocols.sizePolicy().hasHeightForWidth())
        self.tableprotocols.setSizePolicy(sizePolicy)
        self.tableprotocols.setObjectName(_fromUtf8("tableprotocols"))
        self.tableprotocols.verticalHeader().setVisible(False)
        self.verticalLayout_9.addWidget(self.tableprotocols)
        self.label_29 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout_9.addWidget(self.label_29)
        self.textprotoedit = QtGui.QPlainTextEdit(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        self.textprotoedit.setFont(font)
        self.textprotoedit.setObjectName(_fromUtf8("textprotoedit"))
        self.verticalLayout_9.addWidget(self.textprotoedit)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.btnprotoapply = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.btnprotoapply.setIcon(icon1)
        self.btnprotoapply.setObjectName(_fromUtf8("btnprotoapply"))
        self.horizontalLayout_13.addWidget(self.btnprotoapply)
        self.btnprotoreload = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.btnprotoreload.setIcon(icon2)
        self.btnprotoreload.setObjectName(_fromUtf8("btnprotoreload"))
        self.horizontalLayout_13.addWidget(self.btnprotoreload)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.splitterproto)
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_10.addWidget(self.label_14)
        self.texteditdesc_2 = QtGui.QPlainTextEdit(self.verticalLayoutWidget_4)
        self.texteditdesc_2.setReadOnly(True)
        self.texteditdesc_2.setObjectName(_fromUtf8("texteditdesc_2"))
        self.verticalLayout_10.addWidget(self.texteditdesc_2)
        self.horizontalLayout_26.addWidget(self.splitterproto)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/bricks.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_protocols, icon4, _fromUtf8(""))
        self.tab_rules = QtGui.QWidget()
        self.tab_rules.setObjectName(_fromUtf8("tab_rules"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.tab_rules)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.splitter_2 = QtGui.QSplitter(self.tab_rules)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.widget_5 = QtGui.QWidget(self.layoutWidget)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setMargin(2)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.buttondelrule = QtGui.QPushButton(self.widget_5)
        self.buttondelrule.setMaximumSize(QtCore.QSize(30, 16777215))
        self.buttondelrule.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttondelrule.setIcon(icon5)
        self.buttondelrule.setObjectName(_fromUtf8("buttondelrule"))
        self.horizontalLayout_5.addWidget(self.buttondelrule)
        self.buttonaddrule = QtGui.QPushButton(self.widget_5)
        self.buttonaddrule.setMaximumSize(QtCore.QSize(30, 16777215))
        self.buttonaddrule.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonaddrule.setIcon(icon6)
        self.buttonaddrule.setObjectName(_fromUtf8("buttonaddrule"))
        self.horizontalLayout_5.addWidget(self.buttonaddrule)
        self.buttondown = QtGui.QPushButton(self.widget_5)
        self.buttondown.setMaximumSize(QtCore.QSize(30, 16777215))
        self.buttondown.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/arrow_down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttondown.setIcon(icon7)
        self.buttondown.setObjectName(_fromUtf8("buttondown"))
        self.horizontalLayout_5.addWidget(self.buttondown)
        self.buttonup = QtGui.QPushButton(self.widget_5)
        self.buttonup.setMaximumSize(QtCore.QSize(30, 16777215))
        self.buttonup.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/arrow_up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonup.setIcon(icon8)
        self.buttonup.setObjectName(_fromUtf8("buttonup"))
        self.horizontalLayout_5.addWidget(self.buttonup)
        self.verticalLayout_6.addWidget(self.widget_5)
        self.listrules = QtGui.QListView(self.layoutWidget)
        self.listrules.setDragEnabled(True)
        self.listrules.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listrules.setMovement(QtGui.QListView.Free)
        self.listrules.setViewMode(QtGui.QListView.ListMode)
        self.listrules.setObjectName(_fromUtf8("listrules"))
        self.verticalLayout_6.addWidget(self.listrules)
        self.widget = QtGui.QWidget(self.splitter_2)
        self.widget.setToolTip(_fromUtf8(""))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.group = QtGui.QGroupBox(self.widget)
        self.group.setEnabled(False)
        self.group.setObjectName(_fromUtf8("group"))
        self.formLayout = QtGui.QFormLayout(self.group)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_2 = QtGui.QLabel(self.group)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.linename = QtGui.QLineEdit(self.group)
        self.linename.setInputMask(_fromUtf8(""))
        self.linename.setObjectName(_fromUtf8("linename"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.linename)
        self.label_3 = QtGui.QLabel(self.group)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.widget_4 = QtGui.QWidget(self.group)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radio_dir_s2c = QtGui.QRadioButton(self.widget_4)
        self.radio_dir_s2c.setObjectName(_fromUtf8("radio_dir_s2c"))
        self.horizontalLayout_4.addWidget(self.radio_dir_s2c)
        self.radio_dir_c2s = QtGui.QRadioButton(self.widget_4)
        self.radio_dir_c2s.setObjectName(_fromUtf8("radio_dir_c2s"))
        self.horizontalLayout_4.addWidget(self.radio_dir_c2s)
        self.radio_dir_both = QtGui.QRadioButton(self.widget_4)
        self.radio_dir_both.setChecked(True)
        self.radio_dir_both.setObjectName(_fromUtf8("radio_dir_both"))
        self.horizontalLayout_4.addWidget(self.radio_dir_both)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.widget_4)
        self.label_4 = QtGui.QLabel(self.group)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.lineaddr = QtGui.QLineEdit(self.group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineaddr.sizePolicy().hasHeightForWidth())
        self.lineaddr.setSizePolicy(sizePolicy)
        self.lineaddr.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineaddr.setObjectName(_fromUtf8("lineaddr"))
        self.horizontalLayout_10.addWidget(self.lineaddr)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.label_5 = QtGui.QLabel(self.group)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_10.addWidget(self.label_5)
        self.lineport = QtGui.QLineEdit(self.group)
        self.lineport.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineport.setBaseSize(QtCore.QSize(150, 0))
        self.lineport.setMaxLength(6)
        self.lineport.setCursorPosition(0)
        self.lineport.setObjectName(_fromUtf8("lineport"))
        self.horizontalLayout_10.addWidget(self.lineport)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.label_8 = QtGui.QLabel(self.group)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_8)
        self.widget_6 = QtGui.QWidget(self.group)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.radio_type_nothing = QtGui.QRadioButton(self.widget_6)
        self.radio_type_nothing.setChecked(True)
        self.radio_type_nothing.setObjectName(_fromUtf8("radio_type_nothing"))
        self.horizontalLayout_6.addWidget(self.radio_type_nothing)
        self.radio_type_debug = QtGui.QRadioButton(self.widget_6)
        self.radio_type_debug.setObjectName(_fromUtf8("radio_type_debug"))
        self.horizontalLayout_6.addWidget(self.radio_type_debug)
        self.radio_type_muck = QtGui.QRadioButton(self.widget_6)
        self.radio_type_muck.setObjectName(_fromUtf8("radio_type_muck"))
        self.horizontalLayout_6.addWidget(self.radio_type_muck)
        self.radio_type_fuzz = QtGui.QRadioButton(self.widget_6)
        self.radio_type_fuzz.setObjectName(_fromUtf8("radio_type_fuzz"))
        self.horizontalLayout_6.addWidget(self.radio_type_fuzz)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.widget_6)
        self.label_9 = QtGui.QLabel(self.group)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_9)
        self.linepayload = QtGui.QLineEdit(self.group)
        self.linepayload.setObjectName(_fromUtf8("linepayload"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.linepayload)
        self.label_6 = QtGui.QLabel(self.group)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_6)
        self.textruleobj = QtGui.QPlainTextEdit(self.group)
        self.textruleobj.setObjectName(_fromUtf8("textruleobj"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.textruleobj)
        self.label_10 = QtGui.QLabel(self.group)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_10)
        self.widget_7 = QtGui.QWidget(self.group)
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget_7)
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.radio_passthru_yes = QtGui.QRadioButton(self.widget_7)
        self.radio_passthru_yes.setObjectName(_fromUtf8("radio_passthru_yes"))
        self.horizontalLayout_7.addWidget(self.radio_passthru_yes)
        self.radio_passthru_no = QtGui.QRadioButton(self.widget_7)
        self.radio_passthru_no.setChecked(True)
        self.radio_passthru_no.setObjectName(_fromUtf8("radio_passthru_no"))
        self.horizontalLayout_7.addWidget(self.radio_passthru_no)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.widget_7)
        self.verticalLayout_7.addWidget(self.group)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.buttonpreviewrule = QtGui.QPushButton(self.widget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/magnifier.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonpreviewrule.setIcon(icon9)
        self.buttonpreviewrule.setObjectName(_fromUtf8("buttonpreviewrule"))
        self.horizontalLayout_8.addWidget(self.buttonpreviewrule)
        self.saverule = QtGui.QPushButton(self.widget)
        self.saverule.setEnabled(False)
        self.saverule.setIcon(icon1)
        self.saverule.setObjectName(_fromUtf8("saverule"))
        self.horizontalLayout_8.addWidget(self.saverule)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11.addWidget(self.splitter_2)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/chart_organisation.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_rules, icon10, _fromUtf8(""))
        self.tab_streams = QtGui.QWidget()
        self.tab_streams.setObjectName(_fromUtf8("tab_streams"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_streams)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.splitter = QtGui.QSplitter(self.tab_streams)
        self.splitter.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter.setLineWidth(3)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tablestreams = QtGui.QTableView(self.splitter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.tablestreams.setFont(font)
        self.tablestreams.setMidLineWidth(3)
        self.tablestreams.setAutoScroll(True)
        self.tablestreams.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tablestreams.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablestreams.setGridStyle(QtCore.Qt.SolidLine)
        self.tablestreams.setSortingEnabled(True)
        self.tablestreams.setObjectName(_fromUtf8("tablestreams"))
        self.tablestreams.horizontalHeader().setStretchLastSection(True)
        self.tablestreams.verticalHeader().setVisible(False)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.btnicept = QtGui.QPushButton(self.layoutWidget1)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/control_play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/control_play_blue.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnicept.setIcon(icon11)
        self.btnicept.setCheckable(True)
        self.btnicept.setObjectName(_fromUtf8("btnicept"))
        self.horizontalLayout.addWidget(self.btnicept)
        self.btnauto = QtGui.QPushButton(self.layoutWidget1)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/lightning.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnauto.setIcon(icon12)
        self.btnauto.setCheckable(True)
        self.btnauto.setObjectName(_fromUtf8("btnauto"))
        self.horizontalLayout.addWidget(self.btnauto)
        self.btnsend = QtGui.QPushButton(self.layoutWidget1)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/application_go.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnsend.setIcon(icon13)
        self.btnsend.setObjectName(_fromUtf8("btnsend"))
        self.horizontalLayout.addWidget(self.btnsend)
        self.btnclear = QtGui.QPushButton(self.layoutWidget1)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/application_form_delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnclear.setIcon(icon14)
        self.btnclear.setObjectName(_fromUtf8("btnclear"))
        self.horizontalLayout.addWidget(self.btnclear)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtGui.QTabWidget(self.layoutWidget1)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabtext = QtGui.QWidget()
        self.tabtext.setObjectName(_fromUtf8("tabtext"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabtext)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.btnsavetext = QtGui.QPushButton(self.tabtext)
        self.btnsavetext.setObjectName(_fromUtf8("btnsavetext"))
        self.verticalLayout_2.addWidget(self.btnsavetext)
        self.textstream = QtGui.QPlainTextEdit(self.tabtext)
        self.textstream.setObjectName(_fromUtf8("textstream"))
        self.verticalLayout_2.addWidget(self.textstream)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/page_white_text.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabtext, icon15, _fromUtf8(""))
        self.tabhex = QtGui.QWidget()
        self.tabhex.setObjectName(_fromUtf8("tabhex"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tabhex)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.btnsavehex = QtGui.QPushButton(self.tabhex)
        self.btnsavehex.setObjectName(_fromUtf8("btnsavehex"))
        self.verticalLayout_3.addWidget(self.btnsavehex)
        self.tablehex = QtGui.QTableWidget(self.tabhex)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(10)
        self.tablehex.setFont(font)
        self.tablehex.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.tablehex.setTextElideMode(QtCore.Qt.ElideNone)
        self.tablehex.setRowCount(10)
        self.tablehex.setObjectName(_fromUtf8("tablehex"))
        self.tablehex.setColumnCount(16)
        self.tablehex.setRowCount(10)
        item = QtGui.QTableWidgetItem()
        self.tablehex.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tablehex.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tablehex.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tablehex.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tablehex.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tablehex.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tablehex.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tablehex.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tablehex.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tablehex.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tablehex.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tablehex.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tablehex.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tablehex.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tablehex.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tablehex.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tablehex.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tablehex.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tablehex.setItem(1, 2, item)
        self.tablehex.horizontalHeader().setDefaultSectionSize(22)
        self.tablehex.horizontalHeader().setMinimumSectionSize(22)
        self.tablehex.horizontalHeader().setStretchLastSection(True)
        self.tablehex.verticalHeader().setDefaultSectionSize(18)
        self.tablehex.verticalHeader().setMinimumSectionSize(12)
        self.verticalLayout_3.addWidget(self.tablehex)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/page_white_wrench.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabhex, icon16, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_3.addWidget(self.splitter)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/table.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_streams, icon17, _fromUtf8(""))
        self.tab_advanced = QtGui.QWidget()
        self.tab_advanced.setObjectName(_fromUtf8("tab_advanced"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.tab_advanced)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.tabwidget_advanced = QtGui.QTabWidget(self.tab_advanced)
        self.tabwidget_advanced.setObjectName(_fromUtf8("tabwidget_advanced"))
        self.tabdbview = QtGui.QWidget()
        self.tabdbview.setObjectName(_fromUtf8("tabdbview"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.tabdbview)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.splitter_db = QtGui.QSplitter(self.tabdbview)
        self.splitter_db.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_db.setObjectName(_fromUtf8("splitter_db"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.splitter_db)
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.horizontalLayoutWidget_2)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_15 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_12.addWidget(self.label_15)
        self.textdbsql = QtGui.QPlainTextEdit(self.horizontalLayoutWidget_2)
        self.textdbsql.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(11)
        self.textdbsql.setFont(font)
        self.textdbsql.setObjectName(_fromUtf8("textdbsql"))
        self.verticalLayout_12.addWidget(self.textdbsql)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.btndbexec = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.btndbexec.setIcon(icon12)
        self.btndbexec.setObjectName(_fromUtf8("btndbexec"))
        self.horizontalLayout_14.addWidget(self.btndbexec)
        self.btndbflowsq = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/database_add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btndbflowsq.setIcon(icon18)
        self.btndbflowsq.setObjectName(_fromUtf8("btndbflowsq"))
        self.horizontalLayout_14.addWidget(self.btndbflowsq)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.label_16 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_12.addWidget(self.label_16)
        self.tabledbview = QtGui.QTableView(self.horizontalLayoutWidget_2)
        self.tabledbview.setObjectName(_fromUtf8("tabledbview"))
        self.verticalLayout_12.addWidget(self.tabledbview)
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.splitter_db)
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_17 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_11.addWidget(self.label_17)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.verticalLayoutWidget_5)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayout_11.addWidget(self.plainTextEdit)
        self.horizontalLayout_15.addWidget(self.splitter_db)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/database.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabwidget_advanced.addTab(self.tabdbview, icon19, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.splitter_4 = QtGui.QSplitter(self.tab)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.listWidget_objects = QtGui.QListWidget(self.splitter_4)
        self.listWidget_objects.setObjectName(_fromUtf8("listWidget_objects"))
        self.splitter_3 = QtGui.QSplitter(self.splitter_4)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.treeWidget_objectinspector = QtGui.QTreeWidget(self.splitter_3)
        self.treeWidget_objectinspector.setColumnCount(2)
        self.treeWidget_objectinspector.setObjectName(_fromUtf8("treeWidget_objectinspector"))
        self.treeWidget_objectinspector.headerItem().setText(0, _fromUtf8("1"))
        self.treeWidget_objectinspector.headerItem().setText(1, _fromUtf8("2"))
        self.plainTextEdit_objectInspector = QtGui.QPlainTextEdit(self.splitter_3)
        self.plainTextEdit_objectInspector.setObjectName(_fromUtf8("plainTextEdit_objectInspector"))
        self.verticalLayout_4.addWidget(self.splitter_4)
        self.tabwidget_advanced.addTab(self.tab, _fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.tabwidget_advanced)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/rainbow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_advanced, icon20, _fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.tabWidget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 910, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMallory = QtGui.QMenu(self.menubar)
        self.menuMallory.setObjectName(_fromUtf8("menuMallory"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionFlow_Config = QtGui.QAction(MainWindow)
        self.actionFlow_Config.setObjectName(_fromUtf8("actionFlow_Config"))
        self.actionMallory_Help = QtGui.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMallory_Help.setIcon(icon21)
        self.actionMallory_Help.setObjectName(_fromUtf8("actionMallory_Help"))
        self.actionAbout_Mallory = QtGui.QAction(MainWindow)
        self.actionAbout_Mallory.setIcon(icon9)
        self.actionAbout_Mallory.setObjectName(_fromUtf8("actionAbout_Mallory"))
        self.actionPrint_Money = QtGui.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/money.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint_Money.setIcon(icon22)
        self.actionPrint_Money.setObjectName(_fromUtf8("actionPrint_Money"))
        self.menuMallory.addAction(self.actionPrint_Money)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionMallory_Help)
        self.menuHelp.addAction(self.actionAbout_Mallory)
        self.menubar.addAction(self.menuMallory.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        self.tabwidget_advanced.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Mallory - Transparent MiTM Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setToolTip(QtGui.QApplication.translate("MainWindow", "An IP address to match. Blank for wildcard match.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Networking Interfaces", None, QtGui.QApplication.UnicodeUTF8))
        self.btnsaveifcfg.setText(QtGui.QApplication.translate("MainWindow", "Apply Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.btnrefreshifaces.setText(QtGui.QApplication.translate("MainWindow", "Refresh Interfaces", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.texteditdesc.setPlainText(QtGui.QApplication.translate("MainWindow", "The first step to running Mallory is configuring your networking interfaces. Mallory will not read the current state of iptables. This is a one way (saving/writing) configuration GUI. \n"
"\n"
"MiTM interfaces will be interfaces that are going to have all of their traffic MiTMed. This includes PPP interfaces, such as ppp0, from PPTPD VPN clients as well as any other interfaces that are being used by victims as a gateway. \n"
"\n"
"The outbound interface is one interface used to route the vicitmized and local machine traffic to its destination. This interface needs to be able to access to any network locations the victims are attempting to access. Usually this is the Internet or some local testing servers. \n"
"\n"
"When you are finished click \"Save Configuration\" and Mallory will do the rest. \n"
"\n"
"Note: Saving will completely rewrite your iptables, enable IP forwarding and redirect all traffic.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_interfaces), QtGui.QApplication.translate("MainWindow", "Interfaces", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Configured Protocols", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Protocol Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.btnprotoapply.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.btnprotoreload.setText(QtGui.QApplication.translate("MainWindow", "Reload From Disk", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.texteditdesc_2.setPlainText(QtGui.QApplication.translate("MainWindow", "The second step to running Mallory is configuring your protocol interfaces.\n"
"\n"
"Note: Only protocols that show up with \"Yes\" in the \"Debuggable\" column can be edited in the streams tab. \n"
"\n"
"The protocol configuration text is loaded from protos.ini in the \'src\' directory.  At the top of this file must be the configuration line.\n"
"\n"
"[protocols]\n"
"\n"
"You enter the protocols you desire to be configured. An example protocol is shown below:\n"
"\n"
"http_1: http.HTTP:80\n"
"\n"
"What this says is create an http.HTTP protocol, for server port (destination port) 80 and name it http_1. All names, like http_1, must be unique. All ports must be unique. Failure to create unique names results in the first one loaded to be used. \n"
"\n"
"You may supply comments by starting the line with ; or #. \n"
"\n"
"; Set up HTTP on port 80\n"
"http_1:http.HTTP:80\n"
"\n"
"The current list of valid protocols is:\n"
"http.HTTP\n"
"https.HTTPS\n"
"ssh.SSHProtocol\n"
"sslproto.SSLProtocol\n"
"dnsp.DNS\n"
"\n"
"You must type it in the configuration exactly as shown.\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_protocols), QtGui.QApplication.translate("MainWindow", "Protocols", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setToolTip(QtGui.QApplication.translate("MainWindow", "Listing of current rules", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Rule List", None, QtGui.QApplication.UnicodeUTF8))
        self.buttondown.setToolTip(QtGui.QApplication.translate("MainWindow", "Move the selected rule down one level in precedence", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonup.setToolTip(QtGui.QApplication.translate("MainWindow", "Move the selected rule up one level in precedence", None, QtGui.QApplication.UnicodeUTF8))
        self.group.setTitle(QtGui.QApplication.translate("MainWindow", "Rule Specification", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setToolTip(QtGui.QApplication.translate("MainWindow", "This is the name of the rule. Anything that is a valid python name is valid here. Stick with numbers, letters and lower case letters to make the python style deities happy.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.linename.setText(QtGui.QApplication.translate("MainWindow", "default", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setToolTip(QtGui.QApplication.translate("MainWindow", "The direction the rule should match on. Server 2 Client (S2C) rules will only match. Any may be selected to match both directions.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Direction", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_dir_s2c.setText(QtGui.QApplication.translate("MainWindow", "S2C", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_dir_c2s.setText(QtGui.QApplication.translate("MainWindow", "C2S", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_dir_both.setText(QtGui.QApplication.translate("MainWindow", "Both", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Address", None, QtGui.QApplication.UnicodeUTF8))
        self.lineaddr.setToolTip(QtGui.QApplication.translate("MainWindow", "The IP address that should be matched.", None, QtGui.QApplication.UnicodeUTF8))
        self.lineaddr.setInputMask(QtGui.QApplication.translate("MainWindow", "000.000.000.000;_", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.lineport.setToolTip(QtGui.QApplication.translate("MainWindow", "The port to match. 0 for wildcard match.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_type_nothing.setText(QtGui.QApplication.translate("MainWindow", "Nothing", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_type_debug.setText(QtGui.QApplication.translate("MainWindow", "Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_type_muck.setText(QtGui.QApplication.translate("MainWindow", "Muck", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_type_fuzz.setText(QtGui.QApplication.translate("MainWindow", "Fuzz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setToolTip(QtGui.QApplication.translate("MainWindow", "Specify a string in the payload field. Any time that string is encountered in the payload/stream it will cause the rule to match the packet.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Payload", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Rule can be <span style=\" font-weight:600;\">Nothing</span>, <span style=\" font-weight:600;\">Debug</span> or <span style=\" font-weight:600;\">Muck</span>. </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Muck rules are special and require a comma separated array of mucks. A muck is a sed like regular expression. Muck rules only apply of type <span style=\" font-weight:600;\">Muck</span> is selected.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Muck rules must be separated by a newline character. </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Here are a few examples of valid Muck rules:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#780000;\">\"gzip,deflate/ /1\"</span>,<span style=\" color:#780000;\">\"deflate/ /1\"</span>,<span style=\" color:#780000;\">\"gzip/ /1\"</span>. This rule replaced the strings gzip, deflate, deflate and gzip with a space. Another example would be to replace all upper case characters with the letter \'a\', <span style=\" color:#780000;\">\"[A-Z]/a/g\"</span>, Muck rules are created by the following syntax: [python regex]/replacement/[number of occurences] where g can be used in number of occurences for infinity (and beyond).</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Muck", None, QtGui.QApplication.UnicodeUTF8))
        self.textruleobj.setPlainText(QtGui.QApplication.translate("MainWindow", "\"search/replace/g\"\n"
"\"search/replace/3\"\n"
"\"search/replace/g\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Passthru", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_passthru_yes.setText(QtGui.QApplication.translate("MainWindow", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_passthru_no.setText(QtGui.QApplication.translate("MainWindow", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonpreviewrule.setText(QtGui.QApplication.translate("MainWindow", "Preview Rule", None, QtGui.QApplication.UnicodeUTF8))
        self.saverule.setText(QtGui.QApplication.translate("MainWindow", "Save Rule", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_rules), QtGui.QApplication.translate("MainWindow", "Rules", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Actions:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnicept.setToolTip(QtGui.QApplication.translate("MainWindow", "Tell Mallory the Debugger wants to intercept traffic", None, QtGui.QApplication.UnicodeUTF8))
        self.btnicept.setText(QtGui.QApplication.translate("MainWindow", "Intercept", None, QtGui.QApplication.UnicodeUTF8))
        self.btnauto.setToolTip(QtGui.QApplication.translate("MainWindow", "Automagically send all packets", None, QtGui.QApplication.UnicodeUTF8))
        self.btnauto.setText(QtGui.QApplication.translate("MainWindow", "Auto Send", None, QtGui.QApplication.UnicodeUTF8))
        self.btnsend.setToolTip(QtGui.QApplication.translate("MainWindow", "Send the selected packet", None, QtGui.QApplication.UnicodeUTF8))
        self.btnsend.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.btnclear.setText(QtGui.QApplication.translate("MainWindow", "Clear Streams", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setToolTip(QtGui.QApplication.translate("MainWindow", "Save changes made during text editing", None, QtGui.QApplication.UnicodeUTF8))
        self.btnsavetext.setText(QtGui.QApplication.translate("MainWindow", "Save Text Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabtext), QtGui.QApplication.translate("MainWindow", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.btnsavehex.setToolTip(QtGui.QApplication.translate("MainWindow", "Save changes made during hex editing", None, QtGui.QApplication.UnicodeUTF8))
        self.btnsavehex.setText(QtGui.QApplication.translate("MainWindow", "Save Hex Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.tablehex.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "00", None, QtGui.QApplication.UnicodeUTF8))
        self.tablehex.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.tablehex.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.tablehex.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.tablehex.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.tablehex.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.tablehex.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.tablehex.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.tablehex.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.tablehex.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.tablehex.horizontalHeaderItem(10).setText(QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.tablehex.horizontalHeaderItem(11).setText(QtGui.QApplication.translate("MainWindow", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.tablehex.horizontalHeaderItem(12).setText(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.tablehex.horizontalHeaderItem(13).setText(QtGui.QApplication.translate("MainWindow", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.tablehex.horizontalHeaderItem(14).setText(QtGui.QApplication.translate("MainWindow", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.tablehex.horizontalHeaderItem(15).setText(QtGui.QApplication.translate("MainWindow", "Text", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tablehex.isSortingEnabled()
        self.tablehex.setSortingEnabled(False)
        self.tablehex.item(0, 0).setText(QtGui.QApplication.translate("MainWindow", "AA", None, QtGui.QApplication.UnicodeUTF8))
        self.tablehex.item(0, 1).setText(QtGui.QApplication.translate("MainWindow", "01", None, QtGui.QApplication.UnicodeUTF8))
        self.tablehex.item(1, 2).setText(QtGui.QApplication.translate("MainWindow", "0C", None, QtGui.QApplication.UnicodeUTF8))
        self.tablehex.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabhex), QtGui.QApplication.translate("MainWindow", "Hex", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_streams), QtGui.QApplication.translate("MainWindow", "Streams", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "SQL Query", None, QtGui.QApplication.UnicodeUTF8))
        self.btndbexec.setText(QtGui.QApplication.translate("MainWindow", "Execute SQL", None, QtGui.QApplication.UnicodeUTF8))
        self.btndbflowsq.setText(QtGui.QApplication.translate("MainWindow", "Create Flows Query", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.plainTextEdit.setPlainText(QtGui.QApplication.translate("MainWindow", "This is the traffic database viewier. It is a more advanced user interface element. To use it simply (view all TCP flows), click the \"Create Flows Query\" button and then the \"Execute SQL\" button. This will then show all flows and their releated connections. \n"
"\n"
"To view a full capture of traffic double click the row in question.\n"
"\n"
"To see the schema go to $MALLORYROOT$/db and run \"sqlite3 trafficdb\" to open the  the traffic DB. Then type .schema to see the currently available tables. \n"
"\n"
"To refresh the data, click the Execute SQL button again.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwidget_advanced.setTabText(self.tabwidget_advanced.indexOf(self.tabdbview), QtGui.QApplication.translate("MainWindow", "DB View", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwidget_advanced.setTabText(self.tabwidget_advanced.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "HTTP Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_advanced), QtGui.QApplication.translate("MainWindow", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMallory.setTitle(QtGui.QApplication.translate("MainWindow", "Mallory", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFlow_Config.setText(QtGui.QApplication.translate("MainWindow", "Flow Config", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMallory_Help.setText(QtGui.QApplication.translate("MainWindow", "Mallory Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Mallory.setText(QtGui.QApplication.translate("MainWindow", "About Mallory", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint_Money.setText(QtGui.QApplication.translate("MainWindow", "Print Money", None, QtGui.QApplication.UnicodeUTF8))

import mallory_gui_rc
